set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 5.750 -nets VDD -layer METTP -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 678.730 -nets VDD -layer METTP -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 678.290 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.750 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 11.460 -nets VSS -layer METTP -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 673.020 -nets VSS -layer METTP -width 4.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 668.540 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 16.500 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 85.300 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 158.100 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 230.900 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 303.700 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 376.500 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 449.300 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 523.220 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 596.020 -nets VDD  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 681.290 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 89.020 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 161.820 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 234.620 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 307.420 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 380.220 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 453.020 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 526.940 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 599.740 -nets VSS  -layer METTP -width 2.000 -pitch_within_group 72.990 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 671.540 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 87.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 160.220 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 233.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 305.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 373.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 445.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 518.620 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 591.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 680.730 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 94.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 166.980 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 239.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 312.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 379.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 452.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 525.380 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 598.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 71.940 -start_low_ends coordinate  -start_low_ends_coordinate 9.460 -start_high_ends coordinate  -start_high_ends_coordinate 675.020 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
