set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.750 -nets VDD -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 431.650 -nets VDD -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 431.650 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.750 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 14.460 -nets VSS -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 423.940 -nets VSS -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 421.900 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 16.500 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 56.960 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 96.160 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 136.480 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 176.800 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 217.120 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 257.440 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 296.640 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 336.960 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 377.280 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 61.680 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 100.880 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 141.200 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 181.520 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 221.840 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 262.160 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 301.360 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 341.680 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 382.000 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 424.900 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 56.220 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 95.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 134.620 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 173.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 213.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 257.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 297.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 336.220 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 375.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 434.650 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 62.980 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 102.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 141.380 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 180.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 219.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 264.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 303.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 342.980 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 382.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 40.090 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 426.940 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
