set_property PACKAGE_PIN U9 [get_ports boot_init]
set_property PACKAGE_PIN T8 [get_ports boot_init_o]
set_property PACKAGE_PIN U8 [get_ports mode]
set_property PACKAGE_PIN V9 [get_ports mode_o]
set_property PACKAGE_PIN R7 [get_ports reset]
set_property PACKAGE_PIN R8 [get_ports reset_o]
set_property PACKAGE_PIN R6 [get_ports write]
set_property PACKAGE_PIN T6 [get_ports write_o]
set_property PACKAGE_PIN T5 [get_ports flash_programmed]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN D4 [get_ports TX_UART]
set_property PACKAGE_PIN C4 [get_ports RX_UART]

set_property IOSTANDARD LVCMOS33 [get_ports boot_init]
set_property IOSTANDARD LVCMOS33 [get_ports boot_init_o]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports flash_programmed]
set_property IOSTANDARD LVCMOS33 [get_ports mode]
set_property IOSTANDARD LVCMOS33 [get_ports mode_o]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset_o]
set_property IOSTANDARD LVCMOS33 [get_ports RX_UART]
set_property IOSTANDARD LVCMOS33 [get_ports TX_UART]
set_property IOSTANDARD LVCMOS33 [get_ports write]
set_property IOSTANDARD LVCMOS33 [get_ports write_o]


set_property PACKAGE_PIN H1 [get_ports TX_pin]
set_property IOSTANDARD LVCMOS33 [get_ports TX_pin]

set_property PACKAGE_PIN K2 [get_ports {data_in[0]}]
