set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 6.750 -nets VDD -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1024.330 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1018.530 -nets VDD -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1024.330 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1021.330 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1021.530 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 6.750 -nets VDD -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1021.530 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 14.460 -nets VSS -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 1014.580 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1010.820 -nets VSS -layer METTP -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 1014.580 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1011.580 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 1013.820 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 16.500 -nets VSS -layer METTPL -width 6.000 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 1013.820 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 115.200 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1024.330 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 213.760 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1024.330 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 312.320 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 412.000 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 510.560 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 609.120 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 707.680 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 806.240 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 904.800 -nets VDD  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 214.520 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 119.920 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 1014.580 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 218.480 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 1014.580 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 317.040 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 416.720 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 515.280 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 613.840 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 712.400 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 810.960 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 909.520 -nets VSS  -layer METTP -width 3.000 -pitch_within_group 98.770 -start_low_ends coordinate  -start_low_ends_coordinate 13.500 -start_high_ends coordinate  -start_high_ends_coordinate 221.280 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 112.220 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1021.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 213.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 1021.530 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 313.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 409.020 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 509.820 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 610.620 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 711.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 806.620 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 907.420 -nets VDD  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 3.750 -start_high_ends coordinate  -start_high_ends_coordinate 215.260 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 118.980 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 1013.820 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 219.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 1013.820 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 320.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 415.780 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 516.580 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 617.380 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 718.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 813.380 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 914.180 -nets VSS  -layer METTPL -width 3.000 -pitch_within_group 99.050 -start_low_ends coordinate  -start_low_ends_coordinate 11.460 -start_high_ends coordinate  -start_high_ends_coordinate 219.980 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
